### ISSUE TITLE
GtkTemplate: Very unclear error messages

### ISSUE THREAD

**Issue by genodeftest** [virtuald/pygi-composite-templates#5]
It seems like no matter what I do I always run into the same error message from https://github.com/exaile/exaile/blob/gi/xl/externals/gi_composites.py#L118
This even happens when XML file is invalid (e.g. I don't close a `template` tag or use a `object` tag instead). Could you please make those error messages more specific?

Btw: There is a way to nest git repositories. You could nest this one into the exaile repository using [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules). You can specify a version (commit ID) there.

**Comment by virtuald** [comment]
Yeah, I dislike git submodules. Since this doesn't change often, I'd rather just copy it manually.

I'd recommend not creating template files by hand, but use glade that way you don't have to worry about things like invalid XML. 

What would you rather the error message say? I don't think this code can actually detect the specific error that occurred, you'll have to check out the GTK stderr output for that.

**Comment by genodeftest** [comment]
If the XML file is invalid, I want to see an error about an invalid XML file.
In my case I have triple-checked all component names in python source code and glade .ui file and I hope they are 100% correct. Anyways I am seeing this error message:

```
AttributeError: A missing child widget was set using GtkTemplate.Child and the entiretemplate is now broken (widgets: info_label, progress_box, progressbar_placeholder, info_area, playback_image, action_area, cover_image)
```

So I am running into this error not because any of the child components is specified incorrectly, but because of something else (probably unrelated to child widgets).

See https://gist.github.com/genodeftest/770eb19b3056232ae873 and https://gist.github.com/genodeftest/24c2c7e69c410496d895 from current gi branch (at Force LTR layout for playback controls even in RTL locales., a16e8096d647844d358d0285eb75613afe88a6b0)

**Comment by virtuald** [comment]
I agree that having that error message appear would be great. However, this library does not actually load the XML itself, Gtk is doing it internally. And there doesn't appear to be a way to propagate the error message up to this level. 

I know that when I was debugging this stuff, if there were GTK errors then GTK would yell really loudly on stderr. I'd recommend trying to see if you can convince GTK to give you debug messages, and then we could add a note on how to do that to the code.

**Comment by virtuald** [comment]
If you can push the contents of the gist into a branch that I can check out and run, then I can run it and tell you what GTK errors show up on my side.

**Comment by genodeftest** [comment]
Hm, ok. Look at this branch: https://github.com/genodeftest/exaile/tree/broken-gtktemplate-stuff

Using `G_LOG_LEVEL_INFO=debug` I get a Gtk-CRITICAL in gtk_widget_init_template which I don't understand.

**Comment by virtuald** [comment]
Heh, well, that's better than what I get. On the laptop I have here, it just segfaults and dies with no error message. I won't be able to try it on my linux box until later tonight.

**Comment by genodeftest** [comment]
Oh, did I run into a Gtk/GLib bug? (again…)

**Comment by virtuald** [comment]
Apparently. So when I run it on GTK 3.16, it doesn't segfault, but I get an error message that says:

```
(exaile.py:23251): Gtk-CRITICAL **: gtk_widget_init_template: assertion 'template != NULL' failed
```

That implies to me that there's something wrong with your template, and it didn't parse correctly. But the problem with your template is not immediately apparent to me, it seems like it should work, and glade doesn't complain about it.

**Comment by virtuald** [comment]
Aha! I think I know what the problem is! The problem is that the widget you're using is being subclassed in main.py, and the template gets set on the _class_, and so inheritance does not seem to be allowed here. I'll need to play with it more tomorrow to tease out what's allowed and what isn't, and generate a better error message for you.

**Comment by virtuald** [comment]
See the [subclass branch](https://github.com/virtuald/pygi-composite-templates/tree/subclass) I just pushed, it has the same error message you see. I'll try to either fix it or make sure a better error message shows up when one tries to do this. I suspect that it will need to be disallowed, because of the way that composite templates work.

**Comment by virtuald** [comment]
Ok, so I played with this for about 4 hours... and I'm done with it. It looks like you cannot inherit from a python object that uses templates, without fixes to PyGObject. I will add appropriate checks/warnings that way someone doesn't try to do it accidentally.
